namespace TCoSServer.GameServer.Network
{
  public enum GameMessageIds : ushort
  {
    CONNECT = 0xFFFD,
    DISCONNECT = 0xFFFE,
    C2S_TRAVEL_CONNECT = 0,
    S2C_WORLD_PRE_LOGIN = 1,
    C2S_WORLD_PRE_LOGIN_ACK = 2,
    S2C_WORLD_LOGIN = 3,
    C2S_WORLD_LOGIN_ACK = 4,
    C2S_WORLD_LOGOUT = 5,
    S2C_WORLD_LOGOUT_ACK = 6,
    C2S_TRAVEL_WORLD = 7,
    S2C_TRAVEL_WORLD_ACK = 8,
    S2C_FORCED_LOGOUT = 9,
    S2C_USER_ON_LOGIN = 10,
    S2C_USER_ON_LOGOUT = 11,
    S2C_USER_LEVELUP = 12,
    S2C_USER_SET_CLASS = 13,
    S2C_PLAYER_ADD = 17,
    S2C_NPC_ADD = 18,
    S2C_PET_ADD = 19,
    S2C_LEVELOBJECT_REMOVE = 21,
    S2C_GAME_ACTOR_ADD = 22,
    S2C_INTERACTIVELEVELELEMENT_ADD = 23,
    S2C_GAME_ACTOR_MOVE = 24,
    S2C_GAME_INFO_ADD = 25,
    S2C_GAME_INFO_REMOVE = 26,
    S2C_CS_LOGIN = 27,
    C2S_CS_CREATE_CHARACTER = 28,
    S2C_CS_CREATE_CHARACTER_ACK = 29,
    C2S_CS_DELETE_CHARACTER = 30,
    S2C_CS_DELETE_CHARACTER_ACK = 31,
    C2S_CS_SELECT_CHARACTER = 32,
    S2C_CS_SELECT_CHARACTER_ACK = 33,
    S2C_BASE_PAWN_REMOVE = 34,
    S2R_GAME_PLAYERPAWN_MOVE = 35,
    S2R_GAME_PLAYERPAWN_UPDATEROTATION = 36,

    C2S_GET_TEAM_INFO = 54,
    S2C_GET_TEAM_INFO_ACK = 55,

    C2S_GET_GUILD_INFO = 82,
    S2C_GET_GUILD_INFO_ACK = 83,

    C2S_GET_RELATIONSHIP_INFO = 90,
    S2C_GET_RELATIONSHIP_INFO_ACK = 91,

    S2R_GAME_ACTOR_SV2CLREL_SETENABLED = 95,

    S2C_GAME_CONTROLLER_SV2CL_SETPERSISTENTVARIABLE = 104,

    S2C_GAME_PLAYERCONTROLLER_SV2CL_PONG = 107,

    S2C_GAME_PLAYERCONTROLLER_SV2CL_UPDATENETSTATE = 110,
    S2C_GAME_CHAT_SV2CL_ONMESSAGE = 136,
    C2S_GAME_CHAT_CL2SV_SENDMESSAGE = 137,

    C2S_GAME_EMOTES_CL2SV_EMOTE = 177,

    C2S_GAME_GAMEMASTERUTILS_CL2SV_CSSHIELD = 211,

    C2S_GAME_GAMEMASTERUTILS_CL2SV_CSVIS = 213,

    S2C_GAME_SKILLS_SV2CL_ADDACTIVESKILL = 258,

    C2S_GAME_SKILLS_CL2SV_EXECUTEINDEX = 266,

    S2C_GAME_SKILLS_SV2CL_LEARNSKILL = 269,
    C2S_GAME_SKILLS_CL2SV_LEARNSKILL = 270,

    S2R_GAME_PAWN_SV2CLREL_TELEPORTTO = 336,

    S2C_GAME_PLAYERCHARACTER_SV2CL_UPDATEMONEY = 344,
    S2C_GAME_PLAYERCOMBATSTATE_SV2CL_SHEATHEWEAPON = 345,
    S2C_GAME_PLAYERCOMBATSTATE_SV2CL_DRAWWEAPON = 346,

    C2S_GAME_PLAYERCOMBATSTATE_CL2SV_SWITCHWEAPONTYPE = 348,

    C2S_GAME_PLAYERCOMBATSTATE_CL2SV_DRAWSHEATHEWEAPON = 350,

    S2C_GAME_PLAYERPAWN_SV2CL_FORCEMOVEMENT = 375,
    C2S_GAME_PLAYERPAWN_CL2SV_UPDATEMOVEMENT = 376,
    C2S_GAME_PLAYERPAWN_CL2SV_UPDATEMOVEMENTWITHPHYSICS = 377,
    C2S_GAME_PLAYERPAWN_CL2SV_UPDATEROTATION = 378,

    C2S_GAME_PLAYERSKILLS_CL2SV_SAVESKILLDECKSKILLS = 391,


    S2C_GAME_TRAVEL_SV2CL_TRAVELRESULT = 445,
  }
}
